config/routes.rb
Rails.application.routes.draw do

  root "notes#show"

  resources :notes, :only => [:create, :show, :update]
  resources :users, :only => [:create]
  resources :sessions, :only => [:new, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

      user ||= user.new

      can :manage, Note, {user_id: user.id}

#      if user.admin?
#        can :manage, :all                    #admin can perform any action for all objects
#      end
#
#      can :create, Note                      #any authenticated user can create notes
#      can :update, Note, :user_id => user.id #owner can update or edit his notes
      can :read, Note do |note|              #note is readable for readers and note owner
        note.readers.include?(user) || note.user == user
      end


  end

end

app/models/note.rb
class Note < ActiveRecord::Base

  before_create :add_owner_to_readers

  belongs_to :user
  has_many   :viewers
  has_many   :readers, :through => :viewers, :source =>  :user

  def visible_to=(csreaders) #=> coma seprated strings of readers
    if !csreaders.blank?
      allowed_readers = csreaders.split(',').collect {|reader| reader.strip}

      allowed_readers.each do  |reader_name|
        reader = User.find_or_create_by(:name => reader_name)
        self.readers << reader unless self.readers.include?(reader)
      end

    end
  end

  def visible_to
    self.readers.collect{|u| u.name}.sort.join(', ')
  end

  def add_owner_to_readers
    self.readers << self.user unless  self.readers.include?(self.user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes
  has_many :viewers
  has_many :readable, :through => :viewers, :source => :note

  def admin?
    self.admin
  end


end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authentication_required
    redirect_to root_path if session[:user_id].nil?
  end

  def current_user
    User.find_by(:id => session[:user_id]) unless session[:user_id].nil?
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :authentication_required
  load_and_authorize_resource :only => [:show, :create, :update]

#  rescue_from CanCan::AccessDenied do |exception|
#    redirect_to new_session_path, flash: {:errors => 'Access denied: you are not allowed to access this page'}
#  end

  def index
    @notes = Note.all
    render :index
  end

  def show
    if @note = current_user.notes.find_by(params[:id])
      render :show
    else
      redirect_to new_sessions_path
    end
  end


  def create
     @notes = current_user.notes.create(note_params)
     redirect_to root_path
  end


  def update
      @note = current_user.notes.find(params[:id])
      @note.update(note_params)
      redirect_to root_path
  end

  private

    def note_params
      params.require(:note).permit(:content, :visible_to)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new #login page route
    @user = User.new
    render :new
  end


  def create
    if user = User.find_by(user_params[:name])
      sessions[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      redirect_to new_session_path
    end

  end

  def destroy
    session.clear
  end


  private

  def user_params
    params.require(:user).permit(:name)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
  end

  def show
  end 

  def new
  end

  def create
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CancanLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for note do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :visible_to %>
  <%= f.text_field :visible_to %>
  <%= f.submit 'save' %>
<% end %>

app/views/notes/_note.html.erb
<div class=note>
  <div class=note-content>
    <%= note.content %>
  </div>
  <div class=note-author>
    <%= note.user.name %>
  </div>
  <% if can? :update, note %>
    <%= link_to 'edit', edit_note_path(note) %>
  <% end %>
</div>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<%= render @notes %>

app/views/notes/new.html.erb
<%= render 'form', object: @note %>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>